version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
